config/routes.rb
Geoswap::Application.routes.draw do

match '/rpx/callback', :via => :post
match '/my/recent_check_ins', :via => :get

resources :users do
	member do
		get 'recent_check_ins'
	end
end

resources :locations do
	collection do
       get 'near_by'
  	end
  	resources :check_ins
  end

end

app/models/check_in.rb
class CheckIn < ActiveRecord::Base
  belongs_to :location # every check-in has a related location
end

app/models/location.rb
class Location < ActiveRecord::Base
  
  # only tested on postgresql
  DISTANCE_SQL = "(3959 * acos(cos(radians(:lat)) * cos(radians(lat)) * cos(radians(lng) - radians(:lng)) + sin(radians(:lat)) * sin(radians(lat))))"
  
  has_many :check_ins
  validates :name, :lat, :lng, :presence => true
  
  def self.within(from_lat, from_lng, miles)
    sanitized_distance_sql = send(:sanitize_sql, [DISTANCE_SQL, :lat => from_lat, :lng => from_lng])
    select_sql = '*, ' + sanitized_distance_sql + ' as distance'
    where_sql = sanitized_distance_sql + ' <= ?'
    
    select(select_sql).where(where_sql, miles)
  end
  
  def google_map_img_src(zoom = 14)
    "http://maps.google.com/maps/api/staticmap?sensor=true&center=#{lat},#{lng}&amp;#{zoom}=14&size=300x400&markers=color:blue|label:X|#{lat},#{lng}"
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/check_ins_controller.rb
class CheckInsController < ApplicationController
  
  def new
    @location = Location.find(params[:location_id])
    @check_in = @location.check_ins.build
  end
  
  def create
    @location = Location.find(params[:location_id])
    @check_in = @location.check_ins.create(params[:check_in])
    redirect_to location_check_in_path(@location, @check_in)
  end
  
  def show
    @check_in = CheckIn.find(params[:id])
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

def near_by
    respond_to do |format|
      format.html {}
      format.json { render :json => Location.within(params[:lat], params[:lng], 5) }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/check_ins_helper.rb
module CheckInsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/check_ins/new.html.erb
<h1>New Check In <%= @location.name %></h1>

<%= form_for @check_in, :url => location_check_ins_path(@check_in.location) do |f| %>
	<%= f.label :status %>
	<%= f.text_field :status %>
	<%= f.submit 'Check In!' %>
<% end %>

app/views/check_ins/show.html.erb
<h1>Check In </h1>

<p>Status: <%= @check_in.status %></p>
<p>Created: <%= @check_in.created_at %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Geoswap</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/near_by.html.erb
<h1>Nearby</h1>

<p>You are at:</p>
<ul>
	<li>Lat: <span id="currentLat">Detecting...</span></li>
	<li>Long: <span id="currentLon">Detecting...</span></li>
</ul>

<img id="map">

<p>You are near:</p>
<ol id="near-by-locations">

</ol>
<p>Don't see your Location?  <%= link_to 'Create it!', '#', :id => 'create-location' %></p>

<%= javascript_tag do %>
	document.observe("dom:loaded", function() {
		navigator.geolocation.watchPosition(function(position) {
			$('currentLat').update(position.coords.latitude);
			$('currentLon').update(position.coords.longitude);

			new Ajax.Request('/locations/near_by.json', {
				method: 'get',
				requestHeaders: {'Accept': 'application/json'},
				parameters: {'lat': position.coords.latitude, 'lng': position.coords.longitude},
				onSuccess: function(transport) {
					var image_url = "http://maps.google.com/maps/api/staticmap?sensor=true&center=" + position.coords.latitude + "," +
					                    position.coords.longitude + "&zoom=14&size=300x400&markers=color:blue|label:X|" +
					                    position.coords.latitude + ',' + position.coords.longitude;
					var locations = transport.responseText.evalJSON();
					var html = '';

					locations.each(function(item, index) {
						image_url += "&markers=color:green|label:"+(index+1)+"|"+item.location.lat+','+item.location.lng;
						html += '<li>' + item.location.name.escapeHTML();
						html += ' <a href="/locations/' + item.location.id + '/check_ins/new">Check In</a>';
						html += '</li>';
					});

					$('near-by-locations').update(html);

					$('map').setAttribute('src', image_url);

					var create_link_href = "/locations/new?location[lat]=" + position.coords.latitude + "&location[lng]=" + position.coords.longitude;
					$('create-location').setAttribute('href', create_link_href);
				}
			});
		});
	});
<% end %>